#!/bin/bash

# install all packages in pack.csv
paru -Syyu --noconfirm && paru -S --noconfirm $(sed '1d' pack.csv | awk -F "," '{print $1}' | xargs)

# enable TLP
sudo systemctl enable tlp

# enable touchpad
sudo mkdir -v -p /etc/X11/xorg.conf.d/ && sudo cp -v xorg/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf

# make some directories
mkdir -v -p ~/Images/Screenshots/

# copy all configs
cp -v -r config ~/.config
cp -v -r dots/{.xinitrc,.bashrc} ~/
cp -v -r scripts ~/.scripts

# copy wallpaper
cp -v -r walls ~/Images/Wallpapers

# install plugins for neovim
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && nvim +PlugInstall +qall
